<?php /** @noinspection SpellCheckingInspection */


namespace BABA\Doctrine\ORM;


use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;

class RedisQueryBuilder extends QueryBuilder
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em);
    }

    public function expr()
    {
        return parent::expr(); // TODO: Change the autogenerated stub
    }

    public function setCacheable($cacheable)
    {
        return parent::setCacheable($cacheable); // TODO: Change the autogenerated stub
    }

    public function isCacheable()
    {
        return parent::isCacheable(); // TODO: Change the autogenerated stub
    }

    public function setCacheRegion($cacheRegion)
    {
        return parent::setCacheRegion($cacheRegion); // TODO: Change the autogenerated stub
    }

    public function getCacheRegion()
    {
        return parent::getCacheRegion(); // TODO: Change the autogenerated stub
    }

    public function getLifetime()
    {
        return parent::getLifetime(); // TODO: Change the autogenerated stub
    }

    public function setLifetime($lifetime)
    {
        return parent::setLifetime($lifetime); // TODO: Change the autogenerated stub
    }

    public function getCacheMode()
    {
        return parent::getCacheMode(); // TODO: Change the autogenerated stub
    }

    public function setCacheMode($cacheMode)
    {
        return parent::setCacheMode($cacheMode); // TODO: Change the autogenerated stub
    }

    public function getType()
    {
        return parent::getType(); // TODO: Change the autogenerated stub
    }

    public function getEntityManager()
    {
        return parent::getEntityManager(); // TODO: Change the autogenerated stub
    }

    public function getState()
    {
        return parent::getState(); // TODO: Change the autogenerated stub
    }

    public function getDQL()
    {
        return parent::getDQL(); // TODO: Change the autogenerated stub
    }

    public function getQuery()
    {
        return parent::getQuery(); // TODO: Change the autogenerated stub
    }

    public function getRootAlias()
    {
        return parent::getRootAlias(); // TODO: Change the autogenerated stub
    }

    public function getRootAliases()
    {
        return parent::getRootAliases(); // TODO: Change the autogenerated stub
    }

    public function getAllAliases()
    {
        return parent::getAllAliases(); // TODO: Change the autogenerated stub
    }

    public function getRootEntities()
    {
        return parent::getRootEntities(); // TODO: Change the autogenerated stub
    }

    public function setParameter($key, $value, $type = null)
    {
        return parent::setParameter($key, $value, $type); // TODO: Change the autogenerated stub
    }

    public function setParameters($parameters)
    {
        return parent::setParameters($parameters); // TODO: Change the autogenerated stub
    }

    public function getParameters()
    {
        return parent::getParameters(); // TODO: Change the autogenerated stub
    }

    public function getParameter($key)
    {
        return parent::getParameter($key); // TODO: Change the autogenerated stub
    }

    public function setFirstResult($firstResult)
    {
        return parent::setFirstResult($firstResult); // TODO: Change the autogenerated stub
    }

    public function getFirstResult()
    {
        return parent::getFirstResult(); // TODO: Change the autogenerated stub
    }

    public function setMaxResults($maxResults)
    {
        return parent::setMaxResults($maxResults); // TODO: Change the autogenerated stub
    }

    public function getMaxResults()
    {
        return parent::getMaxResults(); // TODO: Change the autogenerated stub
    }

    public function add($dqlPartName, $dqlPart, $append = false)
    {
        return parent::add($dqlPartName, $dqlPart, $append); // TODO: Change the autogenerated stub
    }

    public function select($select = null)
    {
        return parent::select($select); // TODO: Change the autogenerated stub
    }

    public function distinct($flag = true)
    {
        return parent::distinct($flag); // TODO: Change the autogenerated stub
    }

    public function addSelect($select = null)
    {
        return parent::addSelect($select); // TODO: Change the autogenerated stub
    }

    public function delete($delete = null, $alias = null)
    {
        return parent::delete($delete, $alias); // TODO: Change the autogenerated stub
    }

    public function update($update = null, $alias = null)
    {
        return parent::update($update, $alias); // TODO: Change the autogenerated stub
    }

    public function from($from, $alias, $indexBy = null)
    {
        return parent::from($from, $alias, $indexBy); // TODO: Change the autogenerated stub
    }

    public function indexBy($alias, $indexBy)
    {
        return parent::indexBy($alias, $indexBy); // TODO: Change the autogenerated stub
    }

    public function join($join, $alias, $conditionType = null, $condition = null, $indexBy = null)
    {
        return parent::join($join, $alias, $conditionType, $condition, $indexBy); // TODO: Change the autogenerated stub
    }

    public function innerJoin($join, $alias, $conditionType = null, $condition = null, $indexBy = null)
    {
        return parent::innerJoin($join, $alias, $conditionType, $condition, $indexBy); // TODO: Change the autogenerated stub
    }

    public function leftJoin($join, $alias, $conditionType = null, $condition = null, $indexBy = null)
    {
        return parent::leftJoin($join, $alias, $conditionType, $condition, $indexBy); // TODO: Change the autogenerated stub
    }

    public function set($key, $value)
    {
        return parent::set($key, $value); // TODO: Change the autogenerated stub
    }

    public function where($predicates)
    {
        return parent::where($predicates); // TODO: Change the autogenerated stub
    }

    public function andWhere()
    {
        return parent::andWhere(); // TODO: Change the autogenerated stub
    }

    public function orWhere()
    {
        return parent::orWhere(); // TODO: Change the autogenerated stub
    }

    public function groupBy($groupBy)
    {
        return parent::groupBy($groupBy); // TODO: Change the autogenerated stub
    }

    public function addGroupBy($groupBy)
    {
        return parent::addGroupBy($groupBy); // TODO: Change the autogenerated stub
    }

    public function having($having)
    {
        return parent::having($having); // TODO: Change the autogenerated stub
    }

    public function andHaving($having)
    {
        return parent::andHaving($having); // TODO: Change the autogenerated stub
    }

    public function orHaving($having)
    {
        return parent::orHaving($having); // TODO: Change the autogenerated stub
    }

    public function orderBy($sort, $order = null)
    {
        return parent::orderBy($sort, $order); // TODO: Change the autogenerated stub
    }

    public function addOrderBy($sort, $order = null)
    {
        return parent::addOrderBy($sort, $order); // TODO: Change the autogenerated stub
    }

    public function addCriteria(Criteria $criteria)
    {
        return parent::addCriteria($criteria); // TODO: Change the autogenerated stub
    }

    public function getDQLPart($queryPartName)
    {
        return parent::getDQLPart($queryPartName); // TODO: Change the autogenerated stub
    }

    public function getDQLParts()
    {
        return parent::getDQLParts(); // TODO: Change the autogenerated stub
    }

    public function resetDQLParts($parts = null)
    {
        return parent::resetDQLParts($parts); // TODO: Change the autogenerated stub
    }

    public function resetDQLPart($part)
    {
        return parent::resetDQLPart($part); // TODO: Change the autogenerated stub
    }
}